name: onpr
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push: 
  pull_request:
	branches: 
	  - master 	
jobs:
    run-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g test.js
      - run: test.js -v