name: onpr
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    branches:
      - main
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g test.js
      - run: test.js -v
